### PR TITLE
implements #4

### PR DESCRIPTION
**Pull request by phamhere**
I'm not sure how we're structuring the files but from what I know it's having the components in the root directory. Let me know if you want me to add anything else.

### CODE REVIEW

**Comment by HTMLGhozt** [comment]
The issue with having a `<style>` tag injected into React like this is that style tag will show up in the HTML which is undesirable in my opinion.

screen shot 2019-01-02 at 3 04 27 pm

**Comment by phamhere** [comment]
I separated the css and js into two files.

**Comment by phamhere** [comment]
demo: https://codesandbox.io/s/1823nxz214

**Comment by HTMLGhozt** [comment]
Implements #4 (references this pull in issue #4).

**Pull request merged**
